### ISSUE TITLE
Error: Index out of range in self during the model training

### ISSUE THREAD

**Issue by GopinathCool** [lukas-blecher/LaTeX-OCR#8]
I tried to train the model, in the CPU, but received the below error; not sure what could be the cause?

Loss: 1.0180:   2%|█▉                                                                                   | 421/18013 [09:41<6:45:16,  1.38s/it]
Traceback (most recent call last):
  File "train.py", line 94, in <module>
    train(args)
  File "train.py", line 52, in train
    loss = decoder(tgt_seq, mask=tgt_mask, context=encoded)
  File "/home/devops/Envs/latex_ocr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/devops/Envs/latex_ocr/lib/python3.8/site-packages/x_transformers/autoregressive_wrapper.py", line 102, in forward
    out = self.net(xi, **kwargs)
  File "/home/devops/Envs/latex_ocr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/devops/Envs/latex_ocr/lib/python3.8/site-packages/x_transformers/x_transformers.py", line 738, in forward
    x += self.pos_emb(x)
  File "/home/devops/Envs/latex_ocr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/devops/Envs/latex_ocr/lib/python3.8/site-packages/x_transformers/x_transformers.py", line 107, in forward
    return self.emb(n)[None, :, :]
  File "/home/devops/Envs/latex_ocr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/devops/Envs/latex_ocr/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 156, in forward
    return F.embedding(
  File "/home/devops/Envs/latex_ocr/lib/python3.8/site-packages/torch/nn/functional.py", line 1916, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

**Comment by lukas-blecher** [comment]
I think this error occurs when the sequence is longer than `max_seq_len` which should not happen.
I remember I had troubles here too.
- On what commit are you locally? Because I thought I fixed it by filtering out batches with too long sequence length in 1b92175
- What is the `max_seq_length` you are using? I know that 1024 works. I set it down to 512 because I thought I fixed the issue.

Thanks

**Comment by GopinathCool** [comment]
I am currently working on [https://github.com/lukas-blecher/LaTeX-OCR/commit/1b921750e2cba690ab29ce56e46a6276b6dc0db8](url) commit, I guess the max_seq_length is  1024, but I am still facing the same issue, perhaps do I need to update the input?
I am using your formuale.zip, math.txt and tokenizer.json from the google drive.

**Comment by lukas-blecher** [comment]
Ok I found the bug.
Thanks for submitting the issue!
